/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package former;

import java.awt.Color;

import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author sarmo01
 */
public class FormerJPanel extends javax.swing.JPanel implements Runnable{
    private volatile Thread trad;
    
    
    ArrayList<Form> formList = new ArrayList<>();
    ArrayList<Integer> position = new ArrayList<>();
    FileManager list = new FileManager(); 

    /**
     * Creates new form FormerJPanel
     */
    public FormerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtng = new javax.swing.ButtonGroup();
        btnRensa = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        rbtnRektangel = new javax.swing.JRadioButton();
        rbtnTriangel = new javax.swing.JRadioButton();
        rbtnCirkel = new javax.swing.JRadioButton();
        btnSpara = new javax.swing.JButton();
        btnHämta = new javax.swing.JButton();
        btnStopp = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(570, 461));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnStartItemStateChanged(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        rbtng.add(rbtnRektangel);
        rbtnRektangel.setSelected(true);
        rbtnRektangel.setText("Rektangel");

        rbtng.add(rbtnTriangel);
        rbtnTriangel.setText("Triangel");

        rbtng.add(rbtnCirkel);
        rbtnCirkel.setText("Cirkel");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnHämta.setText("Hämta");
        btnHämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHämtaActionPerformed(evt);
            }
        });

        btnStopp.setText("Start");
        btnStopp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnStoppItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHämta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpara)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(rbtnRektangel)
                .addGap(18, 18, 18)
                .addComponent(rbtnTriangel)
                .addGap(18, 18, 18)
                .addComponent(rbtnCirkel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStopp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRensa)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnRektangel)
                    .addComponent(rbtnTriangel)
                    .addComponent(rbtnCirkel)
                    .addComponent(btnStart)
                    .addComponent(btnRensa))
                .addGap(18, 18, 18)
                .addComponent(btnStopp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnHämta))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        // TODO add your handling code here:
        formList.clear();
        repaint();
    }//GEN-LAST:event_btnRensaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        System.out.println("");
        int MouseX = evt.getX();
        int MouseY = evt.getY();
        /*        
        int b = (int)(Math.random()*101);
        int h = (int)(Math.random()*101);        
        int a = (int)(Math.random()*301);
         */
        int b = (int) (Math.random() * 50) + 50;
        int h = (int) (Math.random() * 50) + 50;
        //int a = (int) (Math.random() * 150) + 50;

        if (this.rbtnRektangel.isSelected()) {
            Rektangel r = new Rektangel(MouseX - b / 2, MouseY - h / 2, b, h, true);
            formList.add(r);
            

        } else if (this.rbtnTriangel.isSelected()) {
            Triangel t = new Triangel(MouseX - b / 2, MouseY + h / 2, b, h, true);
            formList.add(t);
/*
            Triangel t = new Triangel(MouseX - a / 2, MouseY + a / 2, a, a, true);
            formList.add(t);
*/
        } else if (this.rbtnCirkel.isSelected()) {
            Cirkel c = new Cirkel(MouseX - h / 2, MouseY - h / 2, h, true);
            formList.add(c);
          
        }

        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:
        list.saveToFile(formList); 
        
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnHämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHämtaActionPerformed
        // TODO add your handling code here:
        formList = FileManager.readFromFile();
         for (int i = 0; i < formList.size(); i++) {
            formList.get(i);
        }
         repaint();
    }//GEN-LAST:event_btnHämtaActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        //FormerJPanel.setLocation(FormerJPanel.getLocation().x, FormerJPanel.getLocation().y);
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnStartItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnStartItemStateChanged

    private void btnStoppItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnStoppItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==1){
            this.btnStopp.setText("stop");
            this.start();
        }
        else{
            this.btnStopp.setText("start");
            this.stopp();
        }
    }//GEN-LAST:event_btnStoppItemStateChanged

    
    
    public void start(){
        if(trad==null){
            trad = new Thread(this);
            trad.start();
        }
    }
    public void stopp(){
        if(trad!=null){
            trad=null;
        }
        
    }
    @Override
    public void run(){
        Thread thisThread = Thread.currentThread();
        


        while (trad==thisThread){
            try{
                Thread.sleep(30);
            }catch(InterruptedException e){ 
            }
            
            int cc=0;
            int aa = 1;
            int k=0;
           
            int pos = formList.get(k).getXpos();
            System.out.println("p" +pos);
            //position.add(pos);

        while (trad==thisThread){
            try{
                Thread.sleep(5);
            }catch(InterruptedException e){ 
            }
            System.out.println("k"+k);
            k++;
            //pos = formList.get(k).getXpos();
            for (int i = 0; i < formList.size(); i++) {
            //System.out.println("Running " + i + " Time");
            //formList.get(i).move( position.get(i), i);
            
            
            System.out.println("i"+i);
            formList.get(i).move(pos, i);
            
            }
            
            
            repaint();
            
       
            pos+=aa;
            
            if (pos>400){
                 aa=-1;
            } else if (pos<0){
                aa=1;
            }
        }
      
        
          
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        for (int i = 0; i < formList.size(); i++) {
            formList.get(i).draw(g);
            
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHämta;
    private javax.swing.JButton btnRensa;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnStart;
    private javax.swing.JToggleButton btnStopp;
    private javax.swing.JRadioButton rbtnCirkel;
    private javax.swing.JRadioButton rbtnRektangel;
    private javax.swing.JRadioButton rbtnTriangel;
    private javax.swing.ButtonGroup rbtng;
    // End of variables declaration//GEN-END:variables
}
/*
            for (int i = 0; i < formList.size(); i++) {
            //System.out.println("Running " + i + " Time");
            formList.get(i).move(cc, i);
            
}
            repaint();
            //cc++;
            cc+=aa;
            
            if (cc>400){
                 aa=-1;
            } else if (cc<0){
                aa=1;
            }*/