/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package former;

import java.awt.Color;

import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author sarmo01
 */
public class FormerJPanel extends javax.swing.JPanel implements Runnable{
    private volatile Thread trad;
    
    
    ArrayList<Form> formList = new ArrayList<>();
    FileManager list = new FileManager(); 

    /**
     * Creates new form FormerJPanel
     */
    public FormerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtng = new javax.swing.ButtonGroup();
        btnStart = new javax.swing.JButton();
        btnRensa = new javax.swing.JButton();
        rbtnRektangel = new javax.swing.JRadioButton();
        rbtnTriangel = new javax.swing.JRadioButton();
        rbtnCirkel = new javax.swing.JRadioButton();
        btnSpara = new javax.swing.JButton();
        btnHämta = new javax.swing.JButton();
        btnStopp = new javax.swing.JToggleButton();

        btnStart.setText("Start");
        btnStart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnStartItemStateChanged(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(570, 461));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        rbtng.add(rbtnRektangel);
        rbtnRektangel.setSelected(true);
        rbtnRektangel.setText("Rektangel");

        rbtng.add(rbtnTriangel);
        rbtnTriangel.setText("Triangel");

        rbtng.add(rbtnCirkel);
        rbtnCirkel.setText("Cirkel");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnHämta.setText("Hämta");
        btnHämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHämtaActionPerformed(evt);
            }
        });

        btnStopp.setText("Start");
        btnStopp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnStoppItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHämta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpara)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(rbtnRektangel)
                .addGap(18, 18, 18)
                .addComponent(rbtnTriangel)
                .addGap(18, 18, 18)
                .addComponent(rbtnCirkel)
                .addGap(34, 34, 34)
                .addComponent(btnStopp)
                .addGap(30, 30, 30)
                .addComponent(btnRensa)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnRektangel)
                    .addComponent(rbtnTriangel)
                    .addComponent(rbtnCirkel)
                    .addComponent(btnRensa)
                    .addComponent(btnStopp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnHämta))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        // Tömmer formlist
        formList.clear();
        repaint();
    }//GEN-LAST:event_btnRensaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
        //System.out.println("");
        int MouseX = evt.getX();
        int MouseY = evt.getY();
       
        int b = (int) (Math.random() * 50) + 50;
        int h = (int) (Math.random() * 50) + 50;
       
        // skapar objekt
        if (this.rbtnRektangel.isSelected()) {
            Rektangel r = new Rektangel(MouseX - b / 2, MouseY - h / 2, b, h, true);
            r.setDirection(1);
            formList.add(r);
            

        } else if (this.rbtnTriangel.isSelected()) {
            Triangel t = new Triangel(MouseX - b / 2, MouseY + h / 2, b, h, true);
            t.setDirection(1);
            formList.add(t);

        } else if (this.rbtnCirkel.isSelected()) {
            Cirkel c = new Cirkel(MouseX - h / 2, MouseY - h / 2, h, true);
            c.setDirection(1);
            formList.add(c);
          
        }

        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // Sparar till fil
        list.saveToFile(formList); 
        
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnHämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHämtaActionPerformed
        // Läser från fil
        formList = FileManager.readFromFile();
         for (int i = 0; i < formList.size(); i++) {
            formList.get(i);
        }
         repaint();
    }//GEN-LAST:event_btnHämtaActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        //FormerJPanel.setLocation(FormerJPanel.getLocation().x, FormerJPanel.getLocation().y);
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnStartItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnStartItemStateChanged

    private void btnStoppItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnStoppItemStateChanged
        // Start och stopp knapp
        if(evt.getStateChange()==1){
            this.btnStopp.setText("stop");
            this.start();
        }
        else{
            this.btnStopp.setText("start");
            this.stopp();
        }
    }//GEN-LAST:event_btnStoppItemStateChanged

    
    // startar tråd
    public void start(){
        if(trad==null){
            trad = new Thread(this);
            trad.start();
        }
    }
    // stannar tråd
    public void stopp(){
        if(trad!=null){
            trad=null;
        }
        
    }
    @Override //animering av former
    public void run(){
        Thread thisThread = Thread.currentThread();

        while (trad == thisThread) {
            try {
                Thread.sleep(5);
            } catch (InterruptedException e) {
            }

            for (int i = 0; i < formList.size(); i++) {
                formList.get(i).move(1);
            }
            repaint();

        }

    }
    
    @Override // ritar ut former
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        for (int i = 0; i < formList.size(); i++) {
            formList.get(i).draw(g);
            
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHämta;
    private javax.swing.JButton btnRensa;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnStart;
    private javax.swing.JToggleButton btnStopp;
    private javax.swing.JRadioButton rbtnCirkel;
    private javax.swing.JRadioButton rbtnRektangel;
    private javax.swing.JRadioButton rbtnTriangel;
    private javax.swing.ButtonGroup rbtng;
    // End of variables declaration//GEN-END:variables
}
